id: P003183
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W15659
  title: སྤྱོད་འཇུག་གི་འགྲེལ་བཤད་རྒྱལ་སྲས་ཡོན་ཏན་བུམ་བཟང
  author: ''
  volumes:
    6f264d1d77344168a65cad0578d4ec3e:
      image_group_id: I1PD36347
      title: ''
      volume_number: 1
      total_pages: 898
      base_file: v001.txt
